// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ButtonShowCoursesController from "./button_show_courses_controller"
application.register("button-show-courses", ButtonShowCoursesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ShowAttendeesController from "./show_attendees_controller"
application.register("show-attendees", ShowAttendeesController)

import ShowBookingsController from "./show_bookings_controller"
application.register("show-bookings", ShowBookingsController)

// import StarRatingController from "./star_rating_controller"
// application.register("star-rating", StarRatingController)

// import TypedJsController from "./typed_js_controller"
// application.register("typed-js", TypedJsController)

import TypedJsController from "./button_show_courses_controller"
application.register("button_show_courses", ButtonShowCoursesController)
