// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ButtonReviewController from "./button_review_controller"
application.register("button-review", ButtonReviewController)



import DashboardShowFriendsController from "./dashboard_show_friends_controller"
application.register("dashboard-show-friends", DashboardShowFriendsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import ReviewController from "./review_controller"
application.register("review", ReviewController)

import ShowAttendeesController from "./show_attendees_controller"
application.register("show-attendees", ShowAttendeesController)

import ShowBookingsController from "./show_bookings_controller"
application.register("show-bookings", ShowBookingsController)
