meta_product_name: "GimmeGolf"
meta_title: "GimmeGolf - Ace of golf apps"
meta_description: "GimmeGolf is the best way to find a community who enjoy playing golf.
      Book games of up to 4 people at a course convenient to you.
       Meet new people, play with friends, have fun!"
meta_image: "logo2.jpg" # should exist in `app/assets/images/`

